- name: Freshen GitHub for metrics user in VPs
  hosts: all_vps
  remote_user: "{{ superuser }}"
  become_user: metrics
  become: yes
  tasks:
  - name: Freshen GitHub for metrics user in VPs
    git:
      repo: "https://github.com/mdavids/root-metrics-sidnlabs.git"
      dest: /home/metrics/repo
      version: main
